name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Updated to latest version
    - name: Use Node.js
      uses: actions/setup-node@v3 # Updated to latest version
      with:
        node-version: '16' # Updated Node.js version to 16, adjust as per your project's compatibility
        cache: 'npm' # Cache dependencies to speed up workflows
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test
    - name: Build
      run: npm run build
